rabbit1:
  build: ./docker/rabbitmq
  hostname: rabbit1
  ports:
    - "5672:5672"
    - "5671:5671"
    - "15671:15671"
    - "15672:15672"
    - "15673:15673"
    - "15674:15674"
rabbit2:
  build: ./docker/rabbitmq
  hostname: rabbit2
  links:
    - rabbit1
  environment:
    - CLUSTERED=true
    - CLUSTER_WITH=rabbit1
    - RAM_NODE=true
  ports:
    - "5673:5672"
rabbit3:
  build: ./docker/rabbitmq
  hostname: rabbit3
  links:
    - rabbit1
    - rabbit2
  environment:
    - CLUSTERED=true
    - CLUSTER_WITH=rabbit1
  ports:
    - "5674:5672"
